name: Quorum Signer Plugin CI
on:
  pull_request:
    branches: [ main, release/**, hotfix/** ]
  push:
    branches: [ main ]
  workflow_dispatch:  
jobs:
  ci-pipeline:
    uses: partior-libs/controller-3p-pipelines/.github/workflows/pipeline-template-quorum-signer-plugin-ci.yaml@feature/DSO-2995_fix_upload
    with:
      CONTROLLER-REPO: partior-libs/controller-3p-pipelines
      CONTROLLER-REF: feature/DSO-2995_fix_upload
      PROJECT-REPO: ${{ github.repository }}
    secrets: inherit